#ifndef MYSTIC_HERO_SKILLS_PROCESSOR_H
#define MYSTIC_HERO_SKILLS_PROCESSOR_H

#include <godot_cpp/classes/ref_counted.hpp>
#include <godot_cpp/classes/node2d.hpp>
#include <godot_cpp/classes/object.hpp>
#include <godot_cpp/variant/dictionary.hpp>
#include <godot_cpp/variant/array.hpp>
#include <godot_cpp/variant/vector2.hpp>
#include <godot_cpp/variant/utility_functions.hpp>
#include <godot_cpp/core/math.hpp>
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/variant/callable.hpp>
#include <unordered_map>
#include <string>

namespace godot {

class MysticHeroSkills : public RefCounted {
    GDCLASS(MysticHeroSkills, RefCounted);

public:
    // helpers
    static Vector2 get_global_pos(Object* obj);
    static double get_global_pos_x(Object* obj);
    static double get_global_pos_y(Object* obj);
    static void set_global_pos(Object* obj, Vector2 pos);
    static void set_global_pos_x(Object* obj, double x);
    static void set_global_pos_y(Object* obj, double y);
    static double get_hp(Object* obj);
    static double get_max_hp(Object* obj);
    static void set_hp(Object* obj, double v);
    static void set_max_hp(Object* obj, double v);
    static double get_damage(Object* obj);
    static void set_damage(Object* obj, double v);
    static String get_team(Object* obj);
    static String get_hero_type(Object* obj);
    static String get_dmg_school(Object* obj);
    static int get_facing(Object* obj);
    static void set_facing(Object* obj, int v);
    static int get_level(Object* obj);
    static void set_level(Object* obj, int v);
    static double get_base_damage(Object* obj);
    static void set_base_damage(Object* obj, double v);
    static double get_skill_range(Object* obj);
    static double get_attack_range(Object* obj);
    static Dictionary get_skill_data(Object* obj);
    static Variant get_active_skill(Object* obj);
    static void set_active_skill(Object* obj, Variant v);
    static int get_active_skill_timer(Object* obj);
    static void set_active_skill_timer(Object* obj, int v);
    static int get_skill_timer(Object* obj);
    static void set_skill_timer(Object* obj, int v);
    static int get_w_cooldown(Object* obj);
    static void set_w_cooldown(Object* obj, int v);
    static int get_e_cooldown(Object* obj);
    static void set_e_cooldown(Object* obj, int v);
    static int get_r_cooldown(Object* obj);
    static void set_r_cooldown(Object* obj, int v);
    static int get_skill_cooldown_max(Object* obj);
    static int get_w_cooldown_max(Object* obj);
    static int get_e_cooldown_max(Object* obj);
    static int get_r_cooldown_max(Object* obj);
    static double get_speed_frames(Object* obj);
    static void set_speed_frames(Object* obj, double v);
    static double get_attack_cooldown_frames(Object* obj);
    static void set_attack_cooldown_frames(Object* obj, double v);
    // Assign langsung `X.attack_timer = N` (frame) -> detik; bukan max seperti kit_lock.
    static void set_atk_timer_frames(Object* h, Object* target, double frames);
    static bool is_alive(Object* obj);
    static Variant get_kit_value(Object* obj, const String& key, Variant def = Variant());
    static void set_kit_value(Object* obj, const String& key, Variant value);
    static Dictionary get_kit(Object* obj);
    static void set_kit(Object* obj, const Dictionary& d);
    static Object* get_target(Object* obj);
    static void set_target(Object* obj, Variant v);
    static Variant py_or(Variant a, Variant b);
    static bool truthy(Variant v);
    static Array range_array(int n);
    static Dictionary make_dict();
    static Dictionary make_dict(Variant k1, Variant v1);
    static Dictionary make_dict(Variant k1, Variant v1, Variant k2, Variant v2);
    static Dictionary make_dict(Variant k1, Variant v1, Variant k2, Variant v2, Variant k3, Variant v3);
    static Dictionary make_dict(Variant k1, Variant v1, Variant k2, Variant v2, Variant k3, Variant v3, Variant k4, Variant v4);
    static bool in_array(const Array& arr, Variant v);
    static Array make_array();
    static Array make_array(Variant a);
    static Array make_array(Variant a, Variant b);
    static Array make_array(Variant a, Variant b, Variant c);
    static Array make_array(Variant a, Variant b, Variant c, Variant d);

    // BaseSkill helpers
    static double skill_range(Object* h, double fallback = 200.0);
    static Array enemies_in_range(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases, double range_val, Variant center_x = Variant(), Variant center_y = Variant());
    static int deal_aoe(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases, double range_val, double damage_multiplier = 1.0);
    static Object* acquire_target(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases, Variant range_val = Variant());
    static bool has_target(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases, Variant range_val = Variant());
    static int visual_duration(const String& hero_type, const String& key);
    static int visual_duration_kind(const String& kind, const String& hero_type, const String& key);
    static int default_visual_duration(const String& key);
    static bool is_starter_kind(const String& hero_type);
    static void set_active_skill(Object* h, const String& kind, const String& key, Variant duration);
    static void trigger_q(Object* h, const String& kind, double shake_amount = 8.0, Variant visual_duration = Variant());
    static void trigger_w(Object* h, const String& kind, double shake_amount = 5.0, Variant visual_duration = Variant());
    static void trigger_e(Object* h, const String& kind, double shake_amount = 6.0, Variant visual_duration = Variant());
    static void trigger_r(Object* h, const String& kind, double shake_amount = 15.0, Variant visual_duration = Variant());

    // kit bridges
    static Array kit_enemies(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static int kit_skill_damage(Object* h);
    static Dictionary kit_catalog_all(Object* h);
    static Dictionary kit_hero_levels(Object* h);
    static void kit_hit(Object* h, Object* target, int dmg, const String& team, Variant src = Variant(), const String& school = "");
    static void kit_slow(Object* h, Object* target, double amount, double dur_frames);
    static void kit_lock(Object* h, Object* target, double frames);
    static double kit_atk_timer(Object* h, Object* target);
    static bool kit_unit_alive(Object* h, Object* target);
    static bool kit_has_slow(Object* h, Object* target);
    static bool kit_has_atk_timer(Object* h, Object* target);
    static bool kit_has_hp(Object* h, Object* target);
    static void kit_shake(Object* h, double amount);
    static void kit_sound(Object* h, double volume);
    static void kit_popup(Object* h, const String& text, bool critical = false);
    static void kit_skill_proj(Object* h, Object* target, double speed = 13.0);
    static void kit_fx_cast(Object* h, const String& skill);
    static void kit_fx_impact(Object* h, double x, double y, double r, const String& skill);

    static String hero_kind(Object* h);

    static void init_state(Object* h);
    static void update_timers(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool cast_q(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool cast_w(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool cast_e(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool cast_r(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);

    static bool boss_generic(Object* h, const String& skill_key, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool registry_dispatch(Object* h, const String& skill_key, const Array& enemies);
    static void fallback_cast(Object* h, const Array& enemies, const String& skill_key);
    static bool by_pair0(Variant a, Variant b);
    static bool __by_pair0(Variant a, Variant b);

    static void bosshero_init_state(Object* h);
    static void bosshero_update_timers(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static void bosshero_cast_q_mana_break(Object* h, const Array& enemies);
    static void bosshero_cast_w_blink(Object* h);
    static void bosshero_cast_e_counterspell(Object* h, const Array& enemies);
    static void bosshero_cast_r_mana_void(Object* h, const Array& enemies);
    static void bosshero_cast_q_spark_wraith(Object* h, const Array& enemies);
    static void bosshero_cast_w_flux(Object* h);
    static void bosshero_cast_e_magnetic_field(Object* h, const Array& enemies);
    static void bosshero_cast_r_tempest_double(Object* h);
    static void bosshero_cast_q_battle_hunger(Object* h);
    static void bosshero_cast_w_counter_helix(Object* h, const Array& enemies);
    static void bosshero_cast_e_berserkers_call(Object* h, const Array& enemies);
    static void bosshero_cast_r_culling_blade(Object* h);
    static void bosshero_cast_q_mist_coil(Object* h, const Array& enemies);
    static void bosshero_cast_w_aphotic_shield(Object* h, const Array& enemies);
    static void bosshero_cast_e_darkness_gale(Object* h);
    static void bosshero_cast_r_death_sever(Object* h, const Array& enemies);
    static void bosshero_cast_q_acid_spray(Object* h, const Array& enemies);
    static void bosshero_cast_w_unstable_concoction(Object* h, const Array& enemies);
    static void bosshero_cast_e_chemical_rage(Object* h);
    static void bosshero_cast_r_greevils_greed(Object* h, const Array& enemies);
    static void bosshero_cast_q_ice_vortex(Object* h, const Array& enemies);
    static void bosshero_cast_w_chilling_touch(Object* h, const Array& enemies);
    static void bosshero_cast_e_ice_blast(Object* h);
    static void bosshero_cast_r_cold_feet(Object* h, const Array& enemies);
    static void bosshero_cast_q_arctic_burn(Object* h, const Array& enemies);
    static void bosshero_cast_w_splinter_blast(Object* h, const Array& enemies);
    static void bosshero_cast_e_winters_curse(Object* h, const Array& enemies);
    static void bosshero_cast_r_cold_embrace(Object* h, const Array& enemies);
    static void bosshero_cast_q_dragon_breath(Object* h, const Array& enemies);
    static void bosshero_cast_w_dragon_tail(Object* h, const Array& enemies);
    static void bosshero_cast_e_dragon_blood(Object* h);
    static void bosshero_cast_r_elder_dragon_form(Object* h, const Array& enemies);
    static void bosshero_cast_q_krobellus_exorcism(Object* h, const Array& enemies);
    static void bosshero_cast_w_krobellus_silence(Object* h, const Array& enemies);
    static void bosshero_cast_e_krobellus_siphon(Object* h);
    static void bosshero_cast_r_krobellus_crypt(Object* h, const Array& enemies);
    static void bosshero_cast_q_vhalzun_death_pulse(Object* h, const Array& enemies);
    static void bosshero_cast_w_vhalzun_heartstopper(Object* h, const Array& enemies);
    static void bosshero_cast_e_vhalzun_reapers_scythe(Object* h, const Array& enemies);
    static void bosshero_cast_r_vhalzun_ghost_shroud(Object* h, const Array& enemies);
    static void bosshero_cast_q_kunkka_tide(Object* h, const Array& enemies);
    static void bosshero_cast_w_kunkka_xmark(Object* h, const Array& enemies);
    static void bosshero_cast_e_kunkka_ghost(Object* h, const Array& enemies);
    static void bosshero_cast_r_kunkka_torrent(Object* h, const Array& enemies);
    static void bosshero_cast_q_nyxarath_shadowraze(Object* h, const Array& enemies);
    static void bosshero_cast_w_nyxarath_necro(Object* h, const Array& enemies);
    static void bosshero_cast_e_nyxarath_presence(Object* h, const Array& enemies);
    static void bosshero_cast_r_nyxarath_requiem(Object* h, const Array& enemies);
    static void bosshero_cast_q_gravewake_anchor(Object* h, const Array& enemies);
    static void bosshero_cast_w_gravewake_tide(Object* h, const Array& enemies);
    static void bosshero_cast_e_gravewake_shell(Object* h);
    static void bosshero_cast_r_gravewake_ravage(Object* h, const Array& enemies);
    static void bosshero_cast_q_syrentha_riptide(Object* h, const Array& enemies);
    static void bosshero_cast_w_syrentha_song(Object* h, const Array& enemies);
    static void bosshero_cast_e_syrentha_mirror(Object* h);
    static void bosshero_cast_r_syrentha_siren(Object* h, const Array& enemies);
    static void bosshero_cast_q_thalgryn_waveform(Object* h, const Array& enemies);
    static void bosshero_cast_w_thalgryn_adaptive(Object* h, const Array& enemies);
    static void bosshero_cast_e_thalgryn_morph(Object* h);
    static void bosshero_cast_r_thalgryn_replicate(Object* h, const Array& enemies);
    static void bosshero_cast_q_malzareth_disruption(Object* h, const Array& enemies);
    static void bosshero_cast_w_malzareth_soul(Object* h, const Array& enemies);
    static void bosshero_cast_e_malzareth_poison(Object* h, const Array& enemies);
    static void bosshero_cast_r_malzareth_disillusion(Object* h, const Array& enemies);
    static void bosshero_cast_q_akashari_strike(Object* h, const Array& enemies);
    static void bosshero_cast_w_akashari_blink(Object* h, const Array& enemies);
    static void bosshero_cast_e_akashari_scream(Object* h, const Array& enemies);
    static void bosshero_cast_r_akashari_sonic(Object* h, const Array& enemies);
    static void bosshero_cast_q_vorenmarr_bonds(Object* h, const Array& enemies);
    static void bosshero_cast_w_vorenmarr_power(Object* h);
    static void bosshero_cast_e_vorenmarr_upheaval(Object* h, const Array& enemies);
    static void bosshero_cast_r_vorenmarr_golem(Object* h, const Array& enemies);
    static void bosshero_cast_q_kenshiro_swiftslash(Object* h, const Array& enemies);
    static void bosshero_cast_w_kenshiro_assault(Object* h, const Array& enemies);
    static void bosshero_cast_e_kenshiro_gale(Object* h, const Array& enemies);
    static void bosshero_cast_r_kenshiro_supremacy(Object* h, const Array& enemies);
    static void bosshero_cast_q_khazan_chained(Object* h, const Array& enemies);
    static void bosshero_cast_w_khazan_leap(Object* h, const Array& enemies);
    static void bosshero_cast_e_khazan_spin(Object* h, const Array& enemies);
    static void bosshero_cast_r_khazan_vanish(Object* h, const Array& enemies);
    static void bosshero_cast_q_wiro_windcut(Object* h, const Array& enemies);
    static void bosshero_cast_w_wiro_whirl(Object* h, const Array& enemies);
    static void bosshero_cast_e_wiro_dash(Object* h, const Array& enemies);
    static void bosshero_cast_r_wiro_typhoon(Object* h, const Array& enemies);
    static void bosshero_cast_q_naraka_chaos(Object* h, const Array& enemies);
    static void bosshero_cast_w_naraka_shadowstep(Object* h, const Array& enemies);
    static void bosshero_cast_e_naraka_hammer(Object* h, const Array& enemies);
    static void bosshero_cast_r_naraka_execution(Object* h, const Array& enemies);
    static void bosshero_cast_q_krognarr_strike(Object* h, const Array& enemies);
    static void bosshero_cast_w_krognarr_seismic(Object* h, const Array& enemies);
    static void bosshero_cast_e_krognarr_rampart(Object* h, const Array& enemies);
    static void bosshero_cast_r_krognarr_eruption(Object* h, const Array& enemies);
    static void bosshero_cast_q_raz_overdrive(Object* h, const Array& enemies);
    static void bosshero_cast_w_raz_searing(Object* h, const Array& enemies);
    static void bosshero_cast_e_raz_surge(Object* h, const Array& enemies);
    static void bosshero_cast_r_raz_gloom(Object* h, const Array& enemies);
    static void bosshero_cast_q_vraskhan_thorned(Object* h, const Array& enemies);
    static void bosshero_cast_w_vraskhan_leap(Object* h, const Array& enemies);
    static void bosshero_cast_e_vraskhan_deathslash(Object* h, const Array& enemies);
    static void bosshero_cast_r_vraskhan_omni(Object* h, const Array& enemies);
    static void bosshero_cast_q_aurethzar_marksman(Object* h, const Array& enemies);
    static void bosshero_cast_w_aurethzar_piercing(Object* h, const Array& enemies);
    static void bosshero_cast_e_aurethzar_frost(Object* h, const Array& enemies);
    static void bosshero_cast_r_aurethzar_thunder(Object* h, const Array& enemies);
    static void bosshero_cast_q_aeralith_tailwind(Object* h, const Array& enemies);
    static void bosshero_cast_w_aeralith_windblade(Object* h, const Array& enemies);
    static void bosshero_cast_e_aeralith_vacuum(Object* h, const Array& enemies);
    static void bosshero_cast_r_aeralith_skyrider(Object* h, const Array& enemies);
    static void bosshero_cast_q_aurex_shieldcrash(Object* h, const Array& enemies);
    static void bosshero_cast_w_aurex_voltblast(Object* h, const Array& enemies);
    static void bosshero_cast_e_aurex_aegis(Object* h, const Array& enemies);
    static void bosshero_cast_r_aurex_spin(Object* h, const Array& enemies);
    static void bosshero_cast_q_nyxareva_darkslash(Object* h, const Array& enemies);
    static void bosshero_cast_w_nyxareva_mortalwound(Object* h, const Array& enemies);
    static void bosshero_cast_e_nyxareva_sacrifice(Object* h, const Array& enemies);
    static void bosshero_cast_r_nyxareva_avatar(Object* h, const Array& enemies);
    static void bosshero_cast_q_thalakryon_bolt(Object* h, const Array& enemies);
    static void bosshero_cast_w_thalakryon_aquashield(Object* h, const Array& enemies);
    static void bosshero_cast_e_thalakryon_tidalrage(Object* h, const Array& enemies);
    static void bosshero_cast_r_thalakryon_metamorph(Object* h, const Array& enemies);
    static void bosshero_cast_q_aurelix_timebomb(Object* h, const Array& enemies);
    static void bosshero_cast_w_aurelix_will(Object* h, const Array& enemies);
    static void bosshero_cast_e_aurelix_shockwave(Object* h, const Array& enemies);
    static void bosshero_cast_r_aurelix_transcend(Object* h, const Array& enemies);
    static void bosshero_cast_q_aurelyssa_whirlwind(Object* h, const Array& enemies);
    static void bosshero_cast_w_aurelyssa_sweep(Object* h, const Array& enemies);
    static void bosshero_cast_e_aurelyssa_wings(Object* h, const Array& enemies);
    static void bosshero_cast_r_aurelyssa_phantom(Object* h, const Array& enemies);
    static void bosshero_cast_q_vargrath_bloodthirst(Object* h, const Array& enemies);
    static void bosshero_cast_w_vargrath_charge(Object* h, const Array& enemies);
    static void bosshero_cast_e_vargrath_devilstrike(Object* h, const Array& enemies);
    static void bosshero_cast_r_vargrath_souldom(Object* h, const Array& enemies);
    static void bosshero_cast_q_nazulmor_typhoon(Object* h, const Array& enemies);
    static void bosshero_cast_w_nazulmor_aquashield(Object* h, const Array& enemies);
    static void bosshero_cast_e_nazulmor_tidalrage(Object* h, const Array& enemies);
    static void bosshero_cast_r_nazulmor_chaotic(Object* h, const Array& enemies);
    static void bosshero_cast_q_kaeldris_overwhelming(Object* h, const Array& enemies);
    static void bosshero_cast_w_kaeldris_press(Object* h, const Array& enemies);
    static void bosshero_cast_e_kaeldris_moment(Object* h, const Array& enemies);
    static void bosshero_cast_r_kaeldris_duel(Object* h, const Array& enemies);
    static void bosshero_cast_q_pyraklos_spearmars(Object* h, const Array& enemies);
    static void bosshero_cast_w_pyraklos_rebuke(Object* h, const Array& enemies);
    static void bosshero_cast_e_pyraklos_bulwark(Object* h, const Array& enemies);
    static void bosshero_cast_r_pyraklos_arena(Object* h, const Array& enemies);
    static void bosshero_cast_q_velmyrth_dagger(Object* h, const Array& enemies);
    static void bosshero_cast_w_velmyrth_strike(Object* h, const Array& enemies);
    static void bosshero_cast_e_velmyrth_blur(Object* h, const Array& enemies);
    static void bosshero_cast_r_velmyrth_coup(Object* h, const Array& enemies);
    static void bosshero_cast_q_solvarin_purification(Object* h, const Array& enemies);
    static void bosshero_cast_w_solvarin_repel(Object* h, const Array& enemies);
    static void bosshero_cast_e_solvarin_degen(Object* h, const Array& enemies);
    static void bosshero_cast_r_solvarin_guardian(Object* h, const Array& enemies);
    static void bosshero_cast_q_azureth_arcanebolt(Object* h, const Array& enemies);
    static void bosshero_cast_w_azureth_concussive(Object* h, const Array& enemies);
    static void bosshero_cast_e_azureth_ancientseal(Object* h, const Array& enemies);
    static void bosshero_cast_r_azureth_mysticflare(Object* h, const Array& enemies);
    static void bosshero_cast_q_luminar_illuminate(Object* h, const Array& enemies);
    static void bosshero_cast_w_luminar_blindinglight(Object* h, const Array& enemies);
    static void bosshero_cast_e_luminar_wisp(Object* h, const Array& enemies);
    static void bosshero_cast_r_luminar_spiritform(Object* h, const Array& enemies);
    static void bosshero_cast_q_solara_starbreaker(Object* h, const Array& enemies);
    static void bosshero_cast_w_solara_celestialhammer(Object* h, const Array& enemies);
    static void bosshero_cast_e_solara_luminosity(Object* h, const Array& enemies);
    static void bosshero_cast_r_solara_solarguardian(Object* h, const Array& enemies);
    static void bosshero_cast_q_pyraethis_icarusdive(Object* h, const Array& enemies);
    static void bosshero_cast_w_pyraethis_firespirits(Object* h, const Array& enemies);
    static void bosshero_cast_e_pyraethis_sunray(Object* h, const Array& enemies);
    static void bosshero_cast_r_pyraethis_supernova(Object* h, const Array& enemies);
    static void bosshero_cast_q_auroth_ionicedge(Object* h, const Array& enemies);
    static void bosshero_cast_w_auroth_ward(Object* h, const Array& enemies);
    static void bosshero_cast_e_auroth_consecration(Object* h, const Array& enemies);
    static void bosshero_cast_r_auroth_guardian(Object* h, const Array& enemies);
    static void bosshero_cast_q_morvein_puncture(Object* h, const Array& enemies);
    static void bosshero_cast_w_morvein_violentstrike(Object* h, const Array& enemies);
    static void bosshero_cast_e_morvein_spectralcharge(Object* h, const Array& enemies);
    static void bosshero_cast_r_morvein_phantomform(Object* h, const Array& enemies);
    static void bosshero_cast_q_thorvak_seed(Object* h, const Array& enemies);
    static void bosshero_cast_w_thorvak_natureswrath(Object* h, const Array& enemies);
    static void bosshero_cast_e_thorvak_vengeance(Object* h, const Array& enemies);
    static void bosshero_cast_r_thorvak_dryad(Object* h, const Array& enemies);
    static void bosshero_cast_q_yamako_deepforest(Object* h, const Array& enemies);
    static void bosshero_cast_w_yamako_woodcreation(Object* h, const Array& enemies);
    static void bosshero_cast_e_yamako_woodgolem(Object* h, const Array& enemies);
    static void bosshero_cast_r_yamako_kannon(Object* h, const Array& enemies);
    static void bosshero_cast_q_ignirus_searingtorrent(Object* h, const Array& enemies);
    static void bosshero_cast_w_ignirus_flameshot(Object* h, const Array& enemies);
    static void bosshero_cast_e_ignirus_burstfireball(Object* h, const Array& enemies);
    static void bosshero_cast_r_ignirus_vengeance(Object* h, const Array& enemies);
    static void bosshero_cast_q_leoric_fearlesscharge(Object* h, const Array& enemies);
    static void bosshero_cast_w_leoric_sacredhammer(Object* h, const Array& enemies);
    static void bosshero_cast_e_leoric_concealblast(Object* h, const Array& enemies);
    static void bosshero_cast_r_leoric_immortality(Object* h, const Array& enemies);
    static void bosshero_cast_q_shirotaka_hiraishin(Object* h, const Array& enemies);
    static void bosshero_cast_w_shirotaka_waterboundary(Object* h, const Array& enemies);
    static void bosshero_cast_e_shirotaka_shadowclones(Object* h, const Array& enemies);
    static void bosshero_cast_r_shirotaka_paperbomb(Object* h, const Array& enemies);
    static void bosshero_cast_q_seiryukong_boundless(Object* h, const Array& enemies);
    static void bosshero_cast_w_seiryukong_treedance(Object* h, const Array& enemies);
    static void bosshero_cast_e_seiryukong_jingusoldiers(Object* h, const Array& enemies);
    static void bosshero_cast_r_seiryukong_wukong(Object* h, const Array& enemies);
    static void bosshero_cast_q_kaelthorn_bravestfighter(Object* h, const Array& enemies);
    static void bosshero_cast_w_kaelthorn_justiceblade(Object* h, const Array& enemies);
    static void bosshero_cast_e_kaelthorn_defendersassault(Object* h, const Array& enemies);
    static void bosshero_cast_r_kaelthorn_chivalryfists(Object* h, const Array& enemies);
    static void bosshero_cast_q_solvanth_ringpunishment(Object* h, const Array& enemies);
    static void bosshero_cast_w_solvanth_gloriouspathway(Object* h, const Array& enemies);
    static void bosshero_cast_e_solvanth_laworder(Object* h, const Array& enemies);
    static void bosshero_cast_r_solvanth_wrath(Object* h, const Array& enemies);
    static void bosshero_cast_q_xyrael_finch(Object* h, const Array& enemies);
    static void bosshero_cast_w_xyrael_defiant(Object* h, const Array& enemies);
    static void bosshero_cast_e_xyrael_tempest(Object* h, const Array& enemies);
    static void bosshero_cast_r_xyrael_lightness(Object* h, const Array& enemies);
    static void bosshero_cast_q_nyxareth_starsplit(Object* h, const Array& enemies);
    static void bosshero_cast_w_nyxareth_realworld(Object* h, const Array& enemies);
    static void bosshero_cast_e_nyxareth_spacetime(Object* h, const Array& enemies);
    static void bosshero_cast_r_nyxareth_astrorealm(Object* h, const Array& enemies);
    static void bosshero_cast_q_cryssalia_frostshock(Object* h, const Array& enemies);
    static void bosshero_cast_w_cryssalia_bitterfrost(Object* h, const Array& enemies);
    static void bosshero_cast_e_cryssalia_frostbites(Object* h, const Array& enemies);
    static void bosshero_cast_r_cryssalia_coldest(Object* h, const Array& enemies);
    static void bosshero_cast_q_kaelthar_chargingfist(Object* h, const Array& enemies);
    static void bosshero_cast_w_kaelthar_quake(Object* h, const Array& enemies);
    static void bosshero_cast_e_kaelthar_fistcrack(Object* h, const Array& enemies);
    static void bosshero_cast_r_kaelthar_fistbreak(Object* h, const Array& enemies);
    static void bosshero_cast_q_morkhaera_spiritburst(Object* h, const Array& enemies);
    static void bosshero_cast_w_morkhaera_airstrike(Object* h, const Array& enemies);
    static void bosshero_cast_e_morkhaera_energyimpact(Object* h, const Array& enemies);
    static void bosshero_cast_r_morkhaera_ethereal(Object* h, const Array& enemies);
    static void bosshero_cast_q_aurelion_callcourage(Object* h, const Array& enemies);
    static void bosshero_cast_w_aurelion_guardianassault(Object* h, const Array& enemies);
    static void bosshero_cast_e_aurelion_kingscommand(Object* h, const Array& enemies);
    static void bosshero_cast_r_aurelion_kingssummon(Object* h, const Array& enemies);
    static void bosshero_cast_q_akahime_petalbarrage(Object* h, const Array& enemies);
    static void bosshero_cast_w_akahime_soulscroll(Object* h, const Array& enemies);
    static void bosshero_cast_e_akahime_shadow(Object* h, const Array& enemies);
    static void bosshero_cast_r_akahime_higanbana(Object* h, const Array& enemies);
    static void bosshero_cast_q_nyxthrael_ambush(Object* h, const Array& enemies);
    static void bosshero_cast_w_nyxthrael_nightfall(Object* h, const Array& enemies);
    static void bosshero_cast_e_nyxthrael_darknightfall(Object* h, const Array& enemies);
    static void bosshero_cast_r_nyxthrael_shadowbringer(Object* h, const Array& enemies);
    static void bosshero_cast_q_sylvantheros_sprout(Object* h, const Array& enemies);
    static void bosshero_cast_w_sylvantheros_teleport(Object* h, const Array& enemies);
    static void bosshero_cast_e_sylvantheros_treants(Object* h, const Array& enemies);
    static void bosshero_cast_r_sylvantheros_wrath(Object* h, const Array& enemies);
    static void bosshero_cast_q_vaelindra_energywave(Object* h, const Array& enemies);
    static void bosshero_cast_w_vaelindra_spacering(Object* h, const Array& enemies);
    static void bosshero_cast_e_vaelindra_violetrequiem(Object* h, const Array& enemies);
    static void bosshero_cast_r_vaelindra_realm(Object* h, const Array& enemies);
    static void bosshero_cast_q_astraelion_swordfall(Object* h, const Array& enemies);
    static void bosshero_cast_w_astraelion_spiritblade(Object* h, const Array& enemies);
    static void bosshero_cast_e_astraelion_forceescape(Object* h, const Array& enemies);
    static void bosshero_cast_r_astraelion_zeroreturn(Object* h, const Array& enemies);
    static void bosshero_cast_q_morvaenthir_soulfragment(Object* h, const Array& enemies);
    static void bosshero_cast_w_morvaenthir_spiritbind(Object* h, const Array& enemies);
    static void bosshero_cast_e_morvaenthir_essence(Object* h, const Array& enemies);
    static void bosshero_cast_r_morvaenthir_shadowrealm(Object* h, const Array& enemies);
    static void bosshero_cast_q_thornvaegrim_bramble(Object* h, const Array& enemies);
    static void bosshero_cast_w_thornvaegrim_twistedadvance(Object* h, const Array& enemies);
    static void bosshero_cast_e_thornvaegrim_saplingthrow(Object* h, const Array& enemies);
    static void bosshero_cast_r_thornvaegrim_grasp(Object* h, const Array& enemies);
    static void bosshero_cast_q_morthraxis_batimpale(Object* h, const Array& enemies);
    static void bosshero_cast_w_morthraxis_sanguine(Object* h, const Array& enemies);
    static void bosshero_cast_e_morthraxis_phantommob(Object* h, const Array& enemies);
    static void bosshero_cast_r_morthraxis_baleful(Object* h, const Array& enemies);
    static void grimjaw_init_state(Object* h);
    static void grimjaw_update_timers(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool grimjaw_cast_q(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool grimjaw_cast_w(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool grimjaw_cast_e(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool grimjaw_cast_r(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static void kaizen_init_state(Object* h);
    static void kaizen_update_timers(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool kaizen_cast_q(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static void kaizen_cast_steel_wind(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static void kaizen_cast_dash_strike(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool kaizen_cast_w(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool kaizen_cast_e(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool kaizen_cast_r(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static void sylara_init_state(Object* h);
    static void sylara_update_timers(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool sylara_cast_q(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool sylara_cast_w(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool sylara_cast_e(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool sylara_cast_r(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static void sylara_release_powershot(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static void thorne_init_state(Object* h);
    static void thorne_update_timers(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool thorne_cast_q(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool thorne_cast_w(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool thorne_cast_e(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool thorne_cast_r(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static void vex_init_state(Object* h);
    static void vex_update_timers(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool vex_cast_q(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool vex_cast_w(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool vex_cast_e(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool vex_cast_r(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static void zephyr_init_state(Object* h);
    static void zephyr_update_timers(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool zephyr_cast_q(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool zephyr_cast_w(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool zephyr_cast_e(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);
    static bool zephyr_cast_r(Object* h, const Array& all_units, const Array& all_towers, const Array& all_bases);

protected:
    static void _bind_methods();
};

} // namespace godot

#endif // MYSTIC_HERO_SKILLS_PROCESSOR_H