"""AST oracle for the active level-1 Boss smart abilities.

The fixture executes the original Boss smart-AI and cast methods from
bosses/base_boss.py. It covers the first smart-AI slice (Gornak, Morgath,
Drakar, Abaddon, Alchemist, Malzareth, Akashari, Vorenmarr, Nyxarath,
Thalgryn, Syrentha, Gravewake, Kunkka and Razak), plus the source generic
_use_ability fallback.
It does not execute entrance/enrage or render hooks; those are separate
sub-layers.
"""
import ast
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
FIXTURE = Path(__file__).parent / "fixtures/boss_ability_source.json"

from bosses.boss_data import get_all_boss_types  # noqa: E402

SOURCE_STATS = get_all_boss_types()


class Target:
    def __init__(self, x, y, hp=10000, name="target", max_hp=None):
        self.x = float(x)
        self.y = float(y)
        self.hp = int(hp)
        self.max_hp = int(hp if max_hp is None else max_hp)
        self.name = name
        self.alive = True
        self.team = "blue"
        self.speed = 1.0
        self.attack_timer = 0
        self.hits = []
        self.slows = []

    def take_damage(self, damage, *_args, **_kwargs):
        damage = int(damage)
        self.hits.append(damage)
        self.hp = max(0, self.hp - damage)
        if self.hp <= 0:
            self.alive = False

    def apply_slow(self, amount, duration):
        self.slows.append([float(amount), int(duration)])


def source_class():
    tree = ast.parse((ROOT / "bosses/base_boss.py").read_text(encoding="utf-8"))
    original = next(node for node in tree.body if isinstance(node, ast.ClassDef) and node.name == "Boss")
    wanted = {
        "_use_ability",
        "_smart_ai_gornak",
        "_cast_q_mana_break",
        "_cast_w_blink",
        "_cast_e_counterspell",
        "_cast_r_mana_void",
        "_smart_ai_morgath",
        "_cast_q_spark_wraith",
        "_cast_w_flux",
        "_cast_e_magnetic_field",
        "_cast_r_tempest_double",
        "_smart_ai_drakar",
        "_cast_q_battle_hunger",
        "_cast_w_counter_helix",
        "_cast_e_berserkers_call",
        "_cast_r_culling_blade",
        "_smart_ai_abaddon",
        "_cast_q_mist_coil",
        "_smart_ai_alchemist",
        "_cast_q_acid_spray",
        "_cast_w_unstable_concoction",
        "_cast_e_chemical_rage",
        "_cast_r_greevils_greed",
        "_smart_ai_malzareth",
        "_malzareth_q",
        "_malzareth_w",
        "_malzareth_e",
        "_malzareth_r",
        "_smart_ai_akashari",
        "_akashari_q",
        "_akashari_w",
        "_akashari_e",
        "_akashari_r",
        "_smart_ai_vorenmarr",
        "_vorenmarr_q",
        "_vorenmarr_w",
        "_vorenmarr_e",
        "_vorenmarr_r",
        "_smart_ai_nyxarath",
        "_nyxarath_q",
        "_nyxarath_w",
        "_nyxarath_e",
        "_nyxarath_r",
        "_smart_ai_thalgryn",
        "_thalgryn_q",
        "_thalgryn_w",
        "_thalgryn_e",
        "_thalgryn_r",
        "_smart_ai_syrentha",
        "_syrentha_q",
        "_syrentha_w",
        "_syrentha_e",
        "_syrentha_r",
        "_smart_ai_gravewake",
        "_gravewake_q",
        "_gravewake_w",
        "_gravewake_e",
        "_gravewake_r",
        "_smart_ai_kunkka",
        "_cast_q_tide_bringer",
        "_cast_w_x_marks",
        "_cast_e_ghost_ship",
        "_cast_r_torrent",
        "_smart_ai_razak",
        "_razak_q",
        "_razak_w",
        "_razak_e",
        "_razak_r",
        "_cast_w_aphotic_shield",
        "_cast_e_darkness_gale",
        "_cast_r_death_sever",
        "_init_l9_timers",
        "_tick_l9_timers",
        "_l9_stats",
        "_l9_target",
        "_l9_aoe",
        "_smart_ai_kenshiro",
        "_smart_ai_khazan",
        "_smart_ai_wiro",
        "_smart_ai_naraka",
        "_smart_ai_krognarr",
        "_smart_ai_raz",
        "_smart_ai_vraskhan",
        "_smart_ai_aurethzar",
        "_smart_ai_aeralith",
        "_smart_ai_aurex",
        "_smart_ai_nyxareva",
        "_smart_ai_thalakryon",
        "_smart_ai_aurelix",
        "_smart_ai_aurelyssa",
        "_smart_ai_vargrath",
        "_smart_ai_nazulmor",
        "_smart_ai_kaeldris",
        "_smart_ai_pyraklos",
        "_smart_ai_velmyrth",
        "_smart_ai_solvarin",
        "_smart_ai_azureth",
        "_smart_ai_luminar",
        "_smart_ai_solara",
        "_smart_ai_pyraethis",
        "_smart_ai_auroth",
        "_smart_ai_morvein",
        "_smart_ai_thorvak",
        "_smart_ai_yamako",
        "_smart_ai_ignirus",
        "_smart_ai_leoric",
        "_smart_ai_shirotaka",
        "_smart_ai_seiryukong",
        "_smart_ai_kaelthorn",
        "_smart_ai_solvanth",
        "_smart_ai_xyrael",
        "_smart_ai_nyxareth",
        "_smart_ai_cryssalia",
        "_smart_ai_kaelthar",
        "_smart_ai_morkhaera",
        "_smart_ai_aurelion",
        "_smart_ai_akahime",
        "_smart_ai_nyxthrael",
        "_smart_ai_sylvantheros",
        "_smart_ai_vaelindra",
        "_smart_ai_astraelion",
        "_smart_ai_morvaenthir",
        "_smart_ai_thornvaegrim",
        "_smart_ai_morthraxis",
    }
    body = [node for node in original.body if isinstance(node, ast.FunctionDef) and node.name in wanted]
    assert {node.name for node in body} == wanted, "Boss ability methods drifted"
    cls = ast.ClassDef(name="SourceBossAbility", bases=[], keywords=[], body=body, decorator_list=[])
    env = {"math": math}
    exec(compile(ast.fix_missing_locations(ast.Module(body=[cls], type_ignores=[])),
                 "<source boss abilities>", "exec"), env)
    result = env["SourceBossAbility"]

    def stats(self):
        return dict(SOURCE_STATS[self.boss_type])

    def l9_stats(self):
        return dict(SOURCE_STATS[self.boss_type])

    result._get_boss_stats = stats
    result._l9_stats = l9_stats
    result._shake_screen = lambda self, _intensity: None
    return result


def make_boss(cls, kind, hp_ratio=1.0, target=None):
    boss = cls()
    source = SOURCE_STATS[kind]
    boss.boss_type = kind
    boss.boss_class = source["boss_class"]
    boss.team = "red"
    boss.x = 0.0
    boss.y = 0.0
    boss.max_hp = int(source["hp"])
    boss.hp = int(boss.max_hp * hp_ratio)
    boss.damage = int(source["damage"])
    boss.direction = -1
    boss.ability_cooldown_max = int(source.get("ability_cooldown", 0))
    boss.ability_damage = int(source.get("ability_damage", 0))
    boss.ability_range = int(source.get("ability_range", 0))
    boss.ability2_timer = 0
    boss.ability_timer = 0
    boss.ability_active = False
    boss.ability_active_timer = 0
    boss.target = target
    boss.is_enraged = False
    boss.dmg_scaling_mult = 1.0
    boss.skill_down_timer = 0
    boss.skill_down_amount = 0.0
    return boss


def row(boss, targets):
    return {
        "type": boss.boss_type,
        "skill": getattr(boss, "active_skill", None),
        "active_skill_timer": int(getattr(boss, "active_skill_timer", 0)),
        "q_timer": int(getattr(boss, "q_timer", 0)),
        "w_timer": int(getattr(boss, "w_timer", 0)),
        "e_timer": int(getattr(boss, "e_timer", 0)),
        "r_timer": int(getattr(boss, "r_timer", 0)),
        "ability_timer": int(getattr(boss, "ability_timer", 0)),
        "ability_active": bool(getattr(boss, "ability_active", False)),
        "hp": int(boss.hp),
        "damage": int(boss.damage),
        "x": float(boss.x),
        "y": float(boss.y),
        "rage_active": bool(getattr(boss, "rage_active", False)),
        "rage_timer": int(getattr(boss, "rage_timer", 0)),
        "necro_buff_active": bool(getattr(boss, "necro_buff_active", False)),
        "necro_buff_timer": int(getattr(boss, "necro_buff_timer", 0)),
        "presence_active": bool(getattr(boss, "presence_active", False)),
        "presence_timer": int(getattr(boss, "presence_timer", 0)),
        "morph_buff_active": bool(getattr(boss, "morph_buff_active", False)),
        "morph_buff_timer": int(getattr(boss, "morph_buff_timer", 0)),
        "mirror_buff_active": bool(getattr(boss, "mirror_buff_active", False)),
        "mirror_buff_timer": int(getattr(boss, "mirror_buff_timer", 0)),
        "shell_active": bool(getattr(boss, "shell_active", False)),
        "shell_timer": int(getattr(boss, "shell_timer", 0)),
        "rum_buff_active": bool(getattr(boss, "rum_buff_active", False)),
        "rum_buff_timer": int(getattr(boss, "rum_buff_timer", 0)),
        "x_mark_timer": int(getattr(boss, "x_mark_timer", 0)),
        "defense_boost": bool(getattr(boss, "defense_boost", False)),
        "defense_timer": int(getattr(boss, "defense_timer", 0)),
        "flux_active_timer": int(getattr(boss, "flux_active_timer", 0)),
        "clones_active_timer": int(getattr(boss, "clones_active_timer", 0)),
        "targets": [
            {
                "name": target.name,
                "hp": int(target.hp),
                "alive": bool(target.alive),
                "hits": list(target.hits),
                "attack_timer": int(target.attack_timer),
                "slows": list(target.slows),
            }
            for target in targets
        ],
    }


def smart_case(cls, kind, label, hp_ratio, target_specs, distance, method):
    targets = [
        Target(*spec[:4], max_hp=(spec[4] if len(spec) > 4 else None))
        for spec in target_specs
    ]
    boss = make_boss(cls, kind, hp_ratio, targets[0] if targets else None)
    getattr(boss, method)(targets, distance)
    return {"label": label, "result": row(boss, targets)}


def persistent_morgath(cls):
    target = Target(400, 0, name="flux")
    boss = make_boss(cls, "morgath", target=target)
    boss.q_timer = 999
    boss.w_timer = 999
    boss.e_timer = 999
    boss.r_timer = 999
    boss.active_skill_timer = 0
    boss.flux_target = target
    boss.flux_active_timer = 31
    boss.clones_active_timer = 0
    boss._smart_ai_morgath([target], 400)
    return {"label": "morgath_flux_tick", "result": row(boss, [target])}


def persistent_kunkka(cls):
    # X Marks the Spot burst lands on a later tick, so hold every cooldown the
    # way the Morgath flux tick case does and let the mark expire.
    marked = Target(60, 0, name="marked")
    enemies = [marked, Target(150, 0, name="near"), Target(400, 0, name="far")]
    boss = make_boss(cls, "kunkka", target=marked)
    boss.q_timer = 999
    boss.w_timer = 999
    boss.e_timer = 999
    boss.r_timer = 999
    boss.active_skill_timer = 0
    boss.rum_buff_active = False
    boss.rum_buff_timer = 0
    boss.x_mark_target = marked
    boss.x_mark_timer = 1
    boss._smart_ai_kunkka(enemies, 60)
    return {"label": "kunkka_x_mark_burst", "result": row(boss, enemies)}


def generic_case(cls):
    targets = [Target(20, 0, name="near"), Target(100, 0, name="far")]
    boss = make_boss(cls, "abaddon", target=targets[0])
    boss.ability_cooldown_max = 180
    boss.ability_damage = 270
    boss.ability_range = 50
    boss.ability_timer = 0
    boss._use_ability(targets)
    return {"label": "generic_ability", "result": row(boss, targets)}


def source_fixture():
    cls = source_class()
    cases = [
        smart_case(cls, "gornak", "gornak_q", 1.0, [(80, 0, 10000, "target")], 80, "_smart_ai_gornak"),
        smart_case(cls, "gornak", "gornak_blink", 1.0, [(200, 0, 10000, "target")], 200, "_smart_ai_gornak"),
        smart_case(
            cls,
            "gornak",
            "gornak_counterspell",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_gornak",
        ),
        smart_case(cls, "gornak", "gornak_mana_void", 0.3, [(20, 0, 10000, "target")], 20, "_smart_ai_gornak"),
        smart_case(cls, "morgath", "morgath_spark", 1.0, [(330, 0, 10000, "target")], 330, "_smart_ai_morgath"),
        smart_case(cls, "morgath", "morgath_flux", 1.0, [(100, 0, 10000, "target")], 100, "_smart_ai_morgath"),
        smart_case(
            cls,
            "morgath",
            "morgath_field",
            1.0,
            [(20, 0, 10000, "a"), (30, 0, 10000, "b")],
            20,
            "_smart_ai_morgath",
        ),
        smart_case(cls, "morgath", "morgath_clones", 0.4, [(20, 0, 10000, "target")], 20, "_smart_ai_morgath"),
        persistent_morgath(cls),
        smart_case(cls, "drakar", "drakar_rage", 0.3, [(200, 0, 10000, "target")], 200, "_smart_ai_drakar"),
        smart_case(
            cls,
            "drakar",
            "drakar_counter_helix",
            1.0,
            [(20, 0, 10000, "a"), (30, 0, 10000, "b")],
            20,
            "_smart_ai_drakar",
        ),
        smart_case(cls, "drakar", "drakar_call", 0.5, [(200, 0, 10000, "target")], 200, "_smart_ai_drakar"),
        smart_case(cls, "drakar", "drakar_culling", 1.0, [(50, 0, 1000, "target", 10000)], 50, "_smart_ai_drakar"),
        smart_case(cls, "abaddon", "abaddon_coil", 1.0, [(100, 0, 10000, "target")], 100, "_smart_ai_abaddon"),
        smart_case(cls, "abaddon", "abaddon_shield", 0.2, [(20, 0, 10000, "target")], 20, "_smart_ai_abaddon"),
        smart_case(cls, "abaddon", "abaddon_gale", 1.0, [(200, 0, 10000, "target")], 200, "_smart_ai_abaddon"),
        smart_case(
            cls,
            "abaddon",
            "abaddon_death_sever",
            1.0,
            [(20, 0, 10000, "a"), (30, 0, 10000, "b"), (40, 0, 10000, "c")],
            20,
            "_smart_ai_abaddon",
        ),
        smart_case(
            cls,
            "alchemist",
            "alchemist_greevils_greed",
            0.3,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_alchemist",
        ),
        smart_case(
            cls,
            "alchemist",
            "alchemist_chemical_rage",
            0.5,
            [(300, 0, 10000, "target")],
            300,
            "_smart_ai_alchemist",
        ),
        smart_case(
            cls,
            "alchemist",
            "alchemist_unstable_concoction",
            1.0,
            [(100, 0, 10000, "a"), (150, 0, 10000, "b")],
            100,
            "_smart_ai_alchemist",
        ),
        smart_case(
            cls,
            "alchemist",
            "alchemist_acid_spray",
            1.0,
            [(100, 0, 10000, "target")],
            100,
            "_smart_ai_alchemist",
        ),
        smart_case(
            cls,
            "malzareth",
            "malzareth_death_pulse",
            0.3,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_malzareth",
        ),
        smart_case(
            cls,
            "malzareth",
            "malzareth_shadow_word",
            1.0,
            [(100, 0, 10000, "target"), (140, 0, 10000, "splash")],
            100,
            "_smart_ai_malzareth",
        ),
        smart_case(
            cls,
            "malzareth",
            "malzareth_nether_blast",
            1.0,
            [(100, 0, 10000, "target")],
            100,
            "_smart_ai_malzareth",
        ),
        smart_case(
            cls,
            "malzareth",
            "malzareth_void",
            1.0,
            [(270, 0, 10000, "target")],
            270,
            "_smart_ai_malzareth",
        ),
        smart_case(
            cls,
            "akashari",
            "akashari_sonic_scream",
            0.3,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_akashari",
        ),
        smart_case(
            cls,
            "akashari",
            "akashari_scream_of_pain",
            1.0,
            [(100, 0, 10000, "a"), (120, 0, 10000, "b"), (140, 0, 10000, "c")],
            100,
            "_smart_ai_akashari",
        ),
        smart_case(
            cls,
            "akashari",
            "akashari_shadow_strike",
            0.5,
            [(200, 0, 10000, "target"), (220, 0, 10000, "near")],
            200,
            "_smart_ai_akashari",
        ),
        smart_case(
            cls,
            "akashari",
            "akashari_scream",
            1.0,
            [(270, 0, 10000, "target")],
            270,
            "_smart_ai_akashari",
        ),
        smart_case(
            cls,
            "vorenmarr",
            "vorenmarr_chaos_storm",
            0.3,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_vorenmarr",
        ),
        smart_case(
            cls,
            "vorenmarr",
            "vorenmarr_shadow_word",
            0.5,
            [(300, 0, 10000, "target")],
            300,
            "_smart_ai_vorenmarr",
        ),
        smart_case(
            cls,
            "vorenmarr",
            "vorenmarr_rain_of_fire",
            1.0,
            [(100, 0, 10000, "target"), (150, 0, 10000, "near")],
            100,
            "_smart_ai_vorenmarr",
        ),
        smart_case(
            cls,
            "vorenmarr",
            "vorenmarr_chaos_bolt",
            1.0,
            [(270, 0, 10000, "target")],
            270,
            "_smart_ai_vorenmarr",
        ),
        smart_case(
            cls,
            "nyxarath",
            "nyxarath_requiem",
            0.3,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_nyxarath",
        ),
        smart_case(
            cls,
            "nyxarath",
            "nyxarath_presence",
            0.5,
            [(300, 0, 10000, "target")],
            300,
            "_smart_ai_nyxarath",
        ),
        smart_case(
            cls,
            "nyxarath",
            "nyxarath_necromastery",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_nyxarath",
        ),
        smart_case(
            cls,
            "nyxarath",
            "nyxarath_shadowraze",
            1.0,
            [(100, 0, 10000, "target")],
            100,
            "_smart_ai_nyxarath",
        ),
        smart_case(
            cls,
            "thalgryn",
            "thalgryn_replicate",
            0.3,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_thalgryn",
        ),
        smart_case(
            cls,
            "thalgryn",
            "thalgryn_morph",
            0.5,
            [(300, 0, 10000, "target")],
            300,
            "_smart_ai_thalgryn",
        ),
        smart_case(
            cls,
            "thalgryn",
            "thalgryn_waveform",
            1.0,
            [(300, 0, 10000, "target"), (100, 0, 10000, "path")],
            300,
            "_smart_ai_thalgryn",
        ),
        smart_case(
            cls,
            "thalgryn",
            "thalgryn_adaptive_strike",
            1.0,
            [(100, 0, 10000, "target"), (150, 0, 10000, "splash")],
            100,
            "_smart_ai_thalgryn",
        ),
        smart_case(
            cls,
            "syrentha",
            "syrentha_song_of_siren",
            0.3,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_syrentha",
        ),
        smart_case(
            cls,
            "syrentha",
            "syrentha_mirror_image",
            0.5,
            [(300, 0, 10000, "target")],
            300,
            "_smart_ai_syrentha",
        ),
        smart_case(
            cls,
            "syrentha",
            "syrentha_enchanting_song",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_syrentha",
        ),
        smart_case(
            cls,
            "syrentha",
            "syrentha_riptide",
            1.0,
            [(100, 0, 10000, "target"), (150, 50, 10000, "splash")],
            100,
            "_smart_ai_syrentha",
        ),
        smart_case(
            cls,
            "gravewake",
            "gravewake_ravage",
            0.3,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_gravewake",
        ),
        smart_case(
            cls,
            "gravewake",
            "gravewake_kraken_shell",
            0.5,
            [(300, 0, 10000, "target")],
            300,
            "_smart_ai_gravewake",
        ),
        smart_case(
            cls,
            "gravewake",
            "gravewake_tidebringer",
            1.0,
            [(100, 0, 10000, "target"), (150, 60, 10000, "near"), (300, 0, 10000, "far")],
            100,
            "_smart_ai_gravewake",
        ),
        smart_case(
            cls,
            "gravewake",
            "gravewake_anchor_smash",
            1.0,
            [(100, 0, 10000, "target"), (190, 0, 10000, "wave")],
            100,
            "_smart_ai_gravewake",
        ),
        smart_case(
            cls,
            "kunkka",
            "kunkka_torrent",
            0.35,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_kunkka",
        ),
        smart_case(
            cls,
            "kunkka",
            "kunkka_ghost_ship",
            0.5,
            [(250, 0, 10000, "target"), (200, 100, 10000, "off_path")],
            250,
            "_smart_ai_kunkka",
        ),
        smart_case(
            cls,
            "kunkka",
            "kunkka_x_marks",
            1.0,
            [(100, 0, 10000, "target"), (150, 60, 10000, "near")],
            100,
            "_smart_ai_kunkka",
        ),
        smart_case(
            cls,
            "kunkka",
            "kunkka_tide_bringer",
            1.0,
            [(100, 0, 10000, "target"), (240, 0, 10000, "wave")],
            100,
            "_smart_ai_kunkka",
        ),
        persistent_kunkka(cls),
        smart_case(
            cls,
            "razak",
            "razak_firestorm",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_razak",
        ),
        smart_case(
            cls,
            "razak",
            "razak_firefly",
            1.0,
            [(200, 0, 10000, "target"), (60, 0, 10000, "near")],
            200,
            "_smart_ai_razak",
        ),
        smart_case(
            cls,
            "razak",
            "razak_flame_cone",
            1.0,
            [(100, 0, 10000, "target"), (150, 40, 10000, "near")],
            100,
            "_smart_ai_razak",
        ),
        smart_case(
            cls,
            "razak",
            "razak_molotov",
            1.0,
            [(260, 0, 10000, "target"), (100, 0, 10000, "near"), (300, 40, 10000, "splash")],
            260,
            "_smart_ai_razak",
        ),
        smart_case(
            cls,
            "kenshiro",
            "kenshiro_supremacy",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_kenshiro",
        ),
        smart_case(
            cls,
            "kenshiro",
            "kenshiro_assault",
            0.5,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_kenshiro",
        ),
        smart_case(
            cls,
            "kenshiro",
            "kenshiro_gale",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_kenshiro",
        ),
        smart_case(
            cls,
            "kenshiro",
            "kenshiro_swiftslash",
            1.0,
            [(80, 0, 10000, "target")],
            80,
            "_smart_ai_kenshiro",
        ),
        smart_case(
            cls,
            "khazan",
            "khazan_vanishing_execution",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_khazan",
        ),
        smart_case(
            cls,
            "khazan",
            "khazan_spin_carnage",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_khazan",
        ),
        smart_case(
            cls,
            "khazan",
            "khazan_leap_smash",
            1.0,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_khazan",
        ),
        smart_case(
            cls,
            "khazan",
            "khazan_chained_blade",
            1.0,
            [(80, 0, 10000, "target")],
            80,
            "_smart_ai_khazan",
        ),
        smart_case(
            cls,
            "wiro",
            "wiro_typhoon",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_wiro",
        ),
        smart_case(
            cls,
            "wiro",
            "wiro_whirl",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_wiro",
        ),
        smart_case(
            cls,
            "wiro",
            "wiro_dash",
            0.4,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_wiro",
        ),
        smart_case(
            cls,
            "wiro",
            "wiro_wind_cut",
            1.0,
            [(80, 0, 10000, "target")],
            80,
            "_smart_ai_wiro",
        ),
        smart_case(
            cls,
            "naraka",
            "naraka_execute",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_naraka",
        ),
        smart_case(
            cls,
            "naraka",
            "naraka_chain_hammer",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_naraka",
        ),
        smart_case(
            cls,
            "naraka",
            "naraka_shadowstep",
            0.5,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_naraka",
        ),
        smart_case(
            cls,
            "naraka",
            "naraka_chaos",
            1.0,
            [(80, 0, 10000, "target")],
            80,
            "_smart_ai_naraka",
        ),
        smart_case(
            cls,
            "krognarr",
            "krognarr_eruption",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_krognarr",
        ),
        smart_case(
            cls,
            "krognarr",
            "krognarr_rampart",
            0.5,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_krognarr",
        ),
        smart_case(
            cls,
            "krognarr",
            "krognarr_seismic",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_krognarr",
        ),
        smart_case(
            cls,
            "krognarr",
            "krognarr_stone_strike",
            1.0,
            [(80, 0, 10000, "target")],
            80,
            "_smart_ai_krognarr",
        ),
        smart_case(
            cls,
            "raz",
            "raz_gloom_leap",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_raz",
        ),
        smart_case(
            cls,
            "raz",
            "raz_searing_dash",
            0.5,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_raz",
        ),
        smart_case(
            cls,
            "raz",
            "raz_surge",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_raz",
        ),
        smart_case(
            cls,
            "raz",
            "raz_overdrive",
            1.0,
            [(80, 0, 10000, "target")],
            80,
            "_smart_ai_raz",
        ),
        smart_case(
            cls,
            "vraskhan",
            "vraskhan_omni_arms",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_vraskhan",
        ),
        smart_case(
            cls,
            "vraskhan",
            "vraskhan_shadow_leap",
            1.0,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_vraskhan",
        ),
        smart_case(
            cls,
            "vraskhan",
            "vraskhan_death_slash",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_vraskhan",
        ),
        smart_case(
            cls,
            "vraskhan",
            "vraskhan_thorned",
            1.0,
            [(80, 0, 10000, "target")],
            80,
            "_smart_ai_vraskhan",
        ),
        smart_case(
            cls,
            "aurethzar",
            "aurethzar_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_aurethzar",
        ),
        smart_case(
            cls,
            "aurethzar",
            "aurethzar_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_aurethzar",
        ),
        smart_case(
            cls,
            "aurethzar",
            "aurethzar_e",
            1.0,
            [(140, 0, 10000, "target")],
            140,
            "_smart_ai_aurethzar",
        ),
        smart_case(
            cls,
            "aurethzar",
            "aurethzar_q",
            1.0,
            [(300, 0, 10000, "target")],
            300,
            "_smart_ai_aurethzar",
        ),
        smart_case(
            cls,
            "aeralith",
            "aeralith_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_aeralith",
        ),
        smart_case(
            cls,
            "aeralith",
            "aeralith_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_aeralith",
        ),
        smart_case(
            cls,
            "aeralith",
            "aeralith_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_aeralith",
        ),
        smart_case(
            cls,
            "aeralith",
            "aeralith_q",
            1.0,
            [(300, 0, 10000, "target")],
            300,
            "_smart_ai_aeralith",
        ),
        smart_case(
            cls,
            "aurex",
            "aurex_r",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_aurex",
        ),
        smart_case(
            cls,
            "aurex",
            "aurex_e",
            0.5,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_aurex",
        ),
        smart_case(
            cls,
            "aurex",
            "aurex_w",
            1.0,
            [(260, 0, 10000, "target")],
            260,
            "_smart_ai_aurex",
        ),
        smart_case(
            cls,
            "aurex",
            "aurex_q",
            1.0,
            [(140, 0, 10000, "target")],
            140,
            "_smart_ai_aurex",
        ),
        smart_case(
            cls,
            "nyxareva",
            "nyxareva_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_nyxareva",
        ),
        smart_case(
            cls,
            "nyxareva",
            "nyxareva_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_nyxareva",
        ),
        smart_case(
            cls,
            "nyxareva",
            "nyxareva_w",
            0.5,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_nyxareva",
        ),
        smart_case(
            cls,
            "nyxareva",
            "nyxareva_q",
            1.0,
            [(150, 0, 10000, "target")],
            150,
            "_smart_ai_nyxareva",
        ),
        smart_case(
            cls,
            "thalakryon",
            "thalakryon_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_thalakryon",
        ),
        smart_case(
            cls,
            "thalakryon",
            "thalakryon_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_thalakryon",
        ),
        smart_case(
            cls,
            "thalakryon",
            "thalakryon_w",
            0.5499999999999999,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_thalakryon",
        ),
        smart_case(
            cls,
            "thalakryon",
            "thalakryon_q",
            1.0,
            [(320, 0, 10000, "target")],
            320,
            "_smart_ai_thalakryon",
        ),
        smart_case(
            cls,
            "aurelix",
            "aurelix_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_aurelix",
        ),
        smart_case(
            cls,
            "aurelix",
            "aurelix_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_aurelix",
        ),
        smart_case(
            cls,
            "aurelix",
            "aurelix_w",
            0.5,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_aurelix",
        ),
        smart_case(
            cls,
            "aurelix",
            "aurelix_q",
            1.0,
            [(300, 0, 10000, "target")],
            300,
            "_smart_ai_aurelix",
        ),
        smart_case(
            cls,
            "aurelyssa",
            "aurelyssa_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_aurelyssa",
        ),
        smart_case(
            cls,
            "aurelyssa",
            "aurelyssa_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_aurelyssa",
        ),
        smart_case(
            cls,
            "aurelyssa",
            "aurelyssa_w",
            0.5,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_aurelyssa",
        ),
        smart_case(
            cls,
            "aurelyssa",
            "aurelyssa_q",
            1.0,
            [(140, 0, 10000, "target")],
            140,
            "_smart_ai_aurelyssa",
        ),
        smart_case(
            cls,
            "vargrath",
            "vargrath_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_vargrath",
        ),
        smart_case(
            cls,
            "vargrath",
            "vargrath_w",
            1.0,
            [(220, 0, 10000, "target")],
            220,
            "_smart_ai_vargrath",
        ),
        smart_case(
            cls,
            "vargrath",
            "vargrath_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_vargrath",
        ),
        smart_case(
            cls,
            "vargrath",
            "vargrath_q",
            1.0,
            [(140, 0, 10000, "target")],
            140,
            "_smart_ai_vargrath",
        ),
        smart_case(
            cls,
            "nazulmor",
            "nazulmor_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_nazulmor",
        ),
        smart_case(
            cls,
            "nazulmor",
            "nazulmor_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_nazulmor",
        ),
        smart_case(
            cls,
            "nazulmor",
            "nazulmor_w",
            0.5499999999999999,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_nazulmor",
        ),
        smart_case(
            cls,
            "nazulmor",
            "nazulmor_q",
            1.0,
            [(330, 0, 10000, "target")],
            330,
            "_smart_ai_nazulmor",
        ),
        smart_case(
            cls,
            "kaeldris",
            "kaeldris_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_kaeldris",
        ),
        smart_case(
            cls,
            "kaeldris",
            "kaeldris_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_kaeldris",
        ),
        smart_case(
            cls,
            "kaeldris",
            "kaeldris_w",
            1.0,
            [(220, 0, 10000, "target")],
            220,
            "_smart_ai_kaeldris",
        ),
        smart_case(
            cls,
            "kaeldris",
            "kaeldris_q",
            1.0,
            [(140, 0, 10000, "target")],
            140,
            "_smart_ai_kaeldris",
        ),
        smart_case(
            cls,
            "pyraklos",
            "pyraklos_r",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_pyraklos",
        ),
        smart_case(
            cls,
            "pyraklos",
            "pyraklos_e",
            0.45,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_pyraklos",
        ),
        smart_case(
            cls,
            "pyraklos",
            "pyraklos_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_pyraklos",
        ),
        smart_case(
            cls,
            "pyraklos",
            "pyraklos_q",
            1.0,
            [(160, 0, 10000, "target")],
            160,
            "_smart_ai_pyraklos",
        ),
        smart_case(
            cls,
            "velmyrth",
            "velmyrth_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_velmyrth",
        ),
        smart_case(
            cls,
            "velmyrth",
            "velmyrth_w",
            1.0,
            [(230, 0, 10000, "target")],
            230,
            "_smart_ai_velmyrth",
        ),
        smart_case(
            cls,
            "velmyrth",
            "velmyrth_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_velmyrth",
        ),
        smart_case(
            cls,
            "velmyrth",
            "velmyrth_q",
            1.0,
            [(140, 0, 10000, "target")],
            140,
            "_smart_ai_velmyrth",
        ),
        smart_case(
            cls,
            "solvarin",
            "solvarin_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_solvarin",
        ),
        smart_case(
            cls,
            "solvarin",
            "solvarin_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_solvarin",
        ),
        smart_case(
            cls,
            "solvarin",
            "solvarin_w",
            0.5499999999999999,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_solvarin",
        ),
        smart_case(
            cls,
            "solvarin",
            "solvarin_q",
            1.0,
            [(340, 0, 10000, "target")],
            340,
            "_smart_ai_solvarin",
        ),
        smart_case(
            cls,
            "azureth",
            "azureth_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_azureth",
        ),
        smart_case(
            cls,
            "azureth",
            "azureth_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_azureth",
        ),
        smart_case(
            cls,
            "azureth",
            "azureth_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_azureth",
        ),
        smart_case(
            cls,
            "azureth",
            "azureth_q",
            1.0,
            [(380, 0, 10000, "target")],
            380,
            "_smart_ai_azureth",
        ),
        smart_case(
            cls,
            "luminar",
            "luminar_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_luminar",
        ),
        smart_case(
            cls,
            "luminar",
            "luminar_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_luminar",
        ),
        smart_case(
            cls,
            "luminar",
            "luminar_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_luminar",
        ),
        smart_case(
            cls,
            "luminar",
            "luminar_q",
            1.0,
            [(390, 0, 10000, "target")],
            390,
            "_smart_ai_luminar",
        ),
        smart_case(
            cls,
            "solara",
            "solara_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_solara",
        ),
        smart_case(
            cls,
            "solara",
            "solara_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_solara",
        ),
        smart_case(
            cls,
            "solara",
            "solara_e",
            0.6,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_solara",
        ),
        smart_case(
            cls,
            "solara",
            "solara_q",
            1.0,
            [(340, 0, 10000, "target")],
            340,
            "_smart_ai_solara",
        ),
        smart_case(
            cls,
            "pyraethis",
            "pyraethis_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_pyraethis",
        ),
        smart_case(
            cls,
            "pyraethis",
            "pyraethis_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_pyraethis",
        ),
        smart_case(
            cls,
            "pyraethis",
            "pyraethis_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_pyraethis",
        ),
        smart_case(
            cls,
            "pyraethis",
            "pyraethis_q",
            1.0,
            [(410, 0, 10000, "target")],
            410,
            "_smart_ai_pyraethis",
        ),
        smart_case(
            cls,
            "auroth",
            "auroth_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_auroth",
        ),
        smart_case(
            cls,
            "auroth",
            "auroth_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_auroth",
        ),
        smart_case(
            cls,
            "auroth",
            "auroth_w",
            0.5499999999999999,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_auroth",
        ),
        smart_case(
            cls,
            "auroth",
            "auroth_q",
            1.0,
            [(330, 0, 10000, "target")],
            330,
            "_smart_ai_auroth",
        ),
        smart_case(
            cls,
            "morvein",
            "morvein_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_morvein",
        ),
        smart_case(
            cls,
            "morvein",
            "morvein_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_morvein",
        ),
        smart_case(
            cls,
            "morvein",
            "morvein_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_morvein",
        ),
        smart_case(
            cls,
            "morvein",
            "morvein_q",
            1.0,
            [(340, 0, 10000, "target")],
            340,
            "_smart_ai_morvein",
        ),
        smart_case(
            cls,
            "thorvak",
            "thorvak_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_thorvak",
        ),
        smart_case(
            cls,
            "thorvak",
            "thorvak_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_thorvak",
        ),
        smart_case(
            cls,
            "thorvak",
            "thorvak_e",
            0.6,
            [(200, 0, 10000, "target")],
            200,
            "_smart_ai_thorvak",
        ),
        smart_case(
            cls,
            "thorvak",
            "thorvak_q",
            1.0,
            [(330, 0, 10000, "target")],
            330,
            "_smart_ai_thorvak",
        ),
        smart_case(
            cls,
            "yamako",
            "yamako_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_yamako",
        ),
        smart_case(
            cls,
            "yamako",
            "yamako_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_yamako",
        ),
        smart_case(
            cls,
            "yamako",
            "yamako_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_yamako",
        ),
        smart_case(
            cls,
            "yamako",
            "yamako_q",
            1.0,
            [(380, 0, 10000, "target")],
            380,
            "_smart_ai_yamako",
        ),
        smart_case(
            cls,
            "ignirus",
            "ignirus_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_ignirus",
        ),
        smart_case(
            cls,
            "ignirus",
            "ignirus_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_ignirus",
        ),
        smart_case(
            cls,
            "ignirus",
            "ignirus_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_ignirus",
        ),
        smart_case(
            cls,
            "ignirus",
            "ignirus_q",
            1.0,
            [(390, 0, 10000, "target")],
            390,
            "_smart_ai_ignirus",
        ),
        smart_case(
            cls,
            "leoric",
            "leoric_r",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_leoric",
        ),
        smart_case(
            cls,
            "leoric",
            "leoric_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_leoric",
        ),
        smart_case(
            cls,
            "leoric",
            "leoric_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_leoric",
        ),
        smart_case(
            cls,
            "leoric",
            "leoric_q",
            1.0,
            [(330, 0, 10000, "target")],
            330,
            "_smart_ai_leoric",
        ),
        smart_case(
            cls,
            "shirotaka",
            "shirotaka_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_shirotaka",
        ),
        smart_case(
            cls,
            "shirotaka",
            "shirotaka_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_shirotaka",
        ),
        smart_case(
            cls,
            "shirotaka",
            "shirotaka_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_shirotaka",
        ),
        smart_case(
            cls,
            "shirotaka",
            "shirotaka_q",
            1.0,
            [(340, 0, 10000, "target")],
            340,
            "_smart_ai_shirotaka",
        ),
        smart_case(
            cls,
            "seiryukong",
            "seiryukong_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_seiryukong",
        ),
        smart_case(
            cls,
            "seiryukong",
            "seiryukong_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_seiryukong",
        ),
        smart_case(
            cls,
            "seiryukong",
            "seiryukong_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_seiryukong",
        ),
        smart_case(
            cls,
            "seiryukong",
            "seiryukong_q",
            1.0,
            [(380, 0, 10000, "target")],
            380,
            "_smart_ai_seiryukong",
        ),
        smart_case(
            cls,
            "kaelthorn",
            "kaelthorn_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_kaelthorn",
        ),
        smart_case(
            cls,
            "kaelthorn",
            "kaelthorn_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_kaelthorn",
        ),
        smart_case(
            cls,
            "kaelthorn",
            "kaelthorn_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_kaelthorn",
        ),
        smart_case(
            cls,
            "kaelthorn",
            "kaelthorn_q",
            1.0,
            [(340, 0, 10000, "target")],
            340,
            "_smart_ai_kaelthorn",
        ),
        smart_case(
            cls,
            "solvanth",
            "solvanth_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_solvanth",
        ),
        smart_case(
            cls,
            "solvanth",
            "solvanth_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_solvanth",
        ),
        smart_case(
            cls,
            "solvanth",
            "solvanth_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_solvanth",
        ),
        smart_case(
            cls,
            "solvanth",
            "solvanth_q",
            1.0,
            [(340, 0, 10000, "target")],
            340,
            "_smart_ai_solvanth",
        ),
        smart_case(
            cls,
            "xyrael",
            "xyrael_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_xyrael",
        ),
        smart_case(
            cls,
            "xyrael",
            "xyrael_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_xyrael",
        ),
        smart_case(
            cls,
            "xyrael",
            "xyrael_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_xyrael",
        ),
        smart_case(
            cls,
            "xyrael",
            "xyrael_q",
            1.0,
            [(340, 0, 10000, "target")],
            340,
            "_smart_ai_xyrael",
        ),
        smart_case(
            cls,
            "nyxareth",
            "nyxareth_4",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_nyxareth",
        ),
        smart_case(
            cls,
            "nyxareth",
            "nyxareth_3",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_nyxareth",
        ),
        smart_case(
            cls,
            "nyxareth",
            "nyxareth_2",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_nyxareth",
        ),
        smart_case(
            cls,
            "nyxareth",
            "nyxareth_1",
            1.0,
            [(400, 0, 10000, "target")],
            400,
            "_smart_ai_nyxareth",
        ),
        smart_case(
            cls,
            "cryssalia",
            "cryssalia_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_cryssalia",
        ),
        smart_case(
            cls,
            "cryssalia",
            "cryssalia_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_cryssalia",
        ),
        smart_case(
            cls,
            "cryssalia",
            "cryssalia_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_cryssalia",
        ),
        smart_case(
            cls,
            "cryssalia",
            "cryssalia_q",
            1.0,
            [(400, 0, 10000, "target")],
            400,
            "_smart_ai_cryssalia",
        ),
        smart_case(
            cls,
            "kaelthar",
            "kaelthar_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_kaelthar",
        ),
        smart_case(
            cls,
            "kaelthar",
            "kaelthar_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_kaelthar",
        ),
        smart_case(
            cls,
            "kaelthar",
            "kaelthar_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_kaelthar",
        ),
        smart_case(
            cls,
            "kaelthar",
            "kaelthar_q",
            1.0,
            [(340, 0, 10000, "target")],
            340,
            "_smart_ai_kaelthar",
        ),
        smart_case(
            cls,
            "morkhaera",
            "morkhaera_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_morkhaera",
        ),
        smart_case(
            cls,
            "morkhaera",
            "morkhaera_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_morkhaera",
        ),
        smart_case(
            cls,
            "morkhaera",
            "morkhaera_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_morkhaera",
        ),
        smart_case(
            cls,
            "morkhaera",
            "morkhaera_q",
            1.0,
            [(400, 0, 10000, "target")],
            400,
            "_smart_ai_morkhaera",
        ),
        smart_case(
            cls,
            "aurelion",
            "aurelion_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_aurelion",
        ),
        smart_case(
            cls,
            "aurelion",
            "aurelion_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_aurelion",
        ),
        smart_case(
            cls,
            "aurelion",
            "aurelion_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_aurelion",
        ),
        smart_case(
            cls,
            "aurelion",
            "aurelion_q",
            1.0,
            [(380, 0, 10000, "target")],
            380,
            "_smart_ai_aurelion",
        ),
        smart_case(
            cls,
            "akahime",
            "akahime_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_akahime",
        ),
        smart_case(
            cls,
            "akahime",
            "akahime_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_akahime",
        ),
        smart_case(
            cls,
            "akahime",
            "akahime_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_akahime",
        ),
        smart_case(
            cls,
            "akahime",
            "akahime_q",
            1.0,
            [(390, 0, 10000, "target")],
            390,
            "_smart_ai_akahime",
        ),
        smart_case(
            cls,
            "nyxthrael",
            "nyxthrael_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_nyxthrael",
        ),
        smart_case(
            cls,
            "nyxthrael",
            "nyxthrael_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_nyxthrael",
        ),
        smart_case(
            cls,
            "nyxthrael",
            "nyxthrael_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_nyxthrael",
        ),
        smart_case(
            cls,
            "nyxthrael",
            "nyxthrael_q",
            1.0,
            [(340, 0, 10000, "target")],
            340,
            "_smart_ai_nyxthrael",
        ),
        smart_case(
            cls,
            "sylvantheros",
            "sylvantheros_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_sylvantheros",
        ),
        smart_case(
            cls,
            "sylvantheros",
            "sylvantheros_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_sylvantheros",
        ),
        smart_case(
            cls,
            "sylvantheros",
            "sylvantheros_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_sylvantheros",
        ),
        smart_case(
            cls,
            "sylvantheros",
            "sylvantheros_q",
            1.0,
            [(400, 0, 10000, "target")],
            400,
            "_smart_ai_sylvantheros",
        ),
        smart_case(
            cls,
            "vaelindra",
            "vaelindra_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_vaelindra",
        ),
        smart_case(
            cls,
            "vaelindra",
            "vaelindra_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_vaelindra",
        ),
        smart_case(
            cls,
            "vaelindra",
            "vaelindra_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_vaelindra",
        ),
        smart_case(
            cls,
            "vaelindra",
            "vaelindra_q",
            1.0,
            [(410, 0, 10000, "target")],
            410,
            "_smart_ai_vaelindra",
        ),
        smart_case(
            cls,
            "astraelion",
            "astraelion_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_astraelion",
        ),
        smart_case(
            cls,
            "astraelion",
            "astraelion_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_astraelion",
        ),
        smart_case(
            cls,
            "astraelion",
            "astraelion_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_astraelion",
        ),
        smart_case(
            cls,
            "astraelion",
            "astraelion_q",
            1.0,
            [(340, 0, 10000, "target")],
            340,
            "_smart_ai_astraelion",
        ),
        smart_case(
            cls,
            "morvaenthir",
            "morvaenthir_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_morvaenthir",
        ),
        smart_case(
            cls,
            "morvaenthir",
            "morvaenthir_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_morvaenthir",
        ),
        smart_case(
            cls,
            "morvaenthir",
            "morvaenthir_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_morvaenthir",
        ),
        smart_case(
            cls,
            "morvaenthir",
            "morvaenthir_q",
            1.0,
            [(400, 0, 10000, "target")],
            400,
            "_smart_ai_morvaenthir",
        ),
        smart_case(
            cls,
            "thornvaegrim",
            "thornvaegrim_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_thornvaegrim",
        ),
        smart_case(
            cls,
            "thornvaegrim",
            "thornvaegrim_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_thornvaegrim",
        ),
        smart_case(
            cls,
            "thornvaegrim",
            "thornvaegrim_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_thornvaegrim",
        ),
        smart_case(
            cls,
            "thornvaegrim",
            "thornvaegrim_q",
            1.0,
            [(340, 0, 10000, "target")],
            340,
            "_smart_ai_thornvaegrim",
        ),
        smart_case(
            cls,
            "morthraxis",
            "morthraxis_r",
            0.4,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b"), (60, 0, 10000, "c")],
            20,
            "_smart_ai_morthraxis",
        ),
        smart_case(
            cls,
            "morthraxis",
            "morthraxis_e",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_morthraxis",
        ),
        smart_case(
            cls,
            "morthraxis",
            "morthraxis_w",
            1.0,
            [(20, 0, 10000, "a"), (40, 0, 10000, "b")],
            20,
            "_smart_ai_morthraxis",
        ),
        smart_case(
            cls,
            "morthraxis",
            "morthraxis_q",
            1.0,
            [(410, 0, 10000, "target")],
            410,
            "_smart_ai_morthraxis",
        ),
        generic_case(cls),
    ]
    return {"cases": cases}


def main():
    actual = source_fixture()
    if "--write" in sys.argv:
        FIXTURE.write_text(json.dumps(actual, indent=2) + "\n", encoding="utf-8")
        print("WROTE: %d source ability cases" % len(actual["cases"]))
    else:
        expected = json.loads(FIXTURE.read_text(encoding="utf-8"))
        assert actual == expected, "Boss ability source drift"
        print("PASS: Boss ability — %d source cases" % len(actual["cases"]))


if __name__ == "__main__":
    main()
