#!/usr/bin/env python3
"""Golden gameplay cases generated by Pygame itself, consumed by Godot tests.

    python tools/test_godot_match_parity.py                 # verify freshness
    python tools/test_godot_match_parity.py --write-fixture # intentional update

No Godot formula is reimplemented here: wave composition, castle escalation,
minion stats and player economy are evaluated using the original Python code.
CI checks this fixture before running GameplayParityTest.tscn. Player saves
are isolated, and this tool never runs the expensive renderer/converter.
"""
import argparse
import ast
import inspect
import json
import os
from pathlib import Path
import sys
import tempfile
import textwrap
from types import SimpleNamespace

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "godot/tests/fixtures/match_parity.json"


def assigned_literal(function, target):
    """Read frame constants which the original game keeps inside its methods."""
    tree = ast.parse(textwrap.dedent(inspect.getsource(function)))
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            if any(ast.unparse(t) == target for t in node.targets):
                return ast.literal_eval(node.value)
    raise AssertionError(f"Pygame assignment disappeared: {target}")


def ai_income_expression(core):
    tree = ast.parse(textwrap.dedent(inspect.getsource(core.Game.update)))
    for node in ast.walk(tree):
        if isinstance(node, ast.AugAssign) and ast.unparse(node.target) == "self.ai.gold":
            # The first such assignment is the passive-income block; subsequent
            # ones are kill rewards. Evaluate the expression in its real globals.
            return compile(ast.Expression(node.value), "<pygame AI income>", "eval")
    raise AssertionError("Pygame AI passive income disappeared")


def make_fixture(core, entity, levels, paths):
    fps = 60
    result = {
        "_generated_by": "tools/test_godot_match_parity.py --write-fixture",
        "rules": {
            "first_wave_delay": assigned_literal(core.Game.reset, "self.wave_timer") / fps,
            "hero_respawn_delay": assigned_literal(
                core.Game.update, "self.hero_respawn_timers[h]") / fps,
            "wave_interval": core.MINION_WAVE_INTERVAL / fps,
            "spawn_delay": core.MINION_SPAWN_DELAY / fps,
            "max_heroes_owned": core.MAX_HEROES_OWNED,
            "ai_starting_gold": entity.AIPlayer().gold,
        },
        "economy": [],
        "waves": [],
        "ai_castle": [],
        "ai_income": [],
        "minions": [],
        "lane_endpoints": {},
    }
    for number in range(1, levels.get_level_count() + 1):
        cfg = levels.get_level_config(number)
        for difficulty in ("easy", "normal", "hard"):
            result["economy"].append({
                "level": number,
                "difficulty": difficulty,
                "gold": core.compute_starting_gold(cfg, number, difficulty),
                "income": core.compute_gold_per_second(number, difficulty),
            })
    waves = (1, 3, 4, 6, 7, 9, 10, 12, 13, 20)
    for castle_level in core.NEXUS_LEVELS:
        for wave in waves:
            game = SimpleNamespace(
                blue_base=SimpleNamespace(level=castle_level),
                red_base=SimpleNamespace(level=castle_level), wave_number=wave)
            result["waves"].append({
                "castle_level": castle_level, "wave": wave,
                "composition": core.Game._get_wave_composition(game, "blue"),
            })
        for kind in core.MINION_TYPES:
            minion = entity.Minion(kind, "blue", "top", castle_level)
            result["minions"].append({
                "type": kind, "castle_level": castle_level,
                "max_hp": minion.max_hp, "damage": minion.damage,
                "move_speed": minion.speed * fps,
                "attack_range": minion.range,
                "attack_cooldown": minion.attack_cooldown / fps,
                "gold_reward": minion.gold_reward,
                "regen_per_second": minion.regen * fps,
                "ai_level": minion.ai_level,
            })
    income_expr = ai_income_expression(core)
    for wave in waves:
        castle = SimpleNamespace(level=1)
        castle.upgrade = lambda: setattr(castle, "level", castle.level + 1)
        game = SimpleNamespace(red_base=castle, wave_number=wave)
        core.Game._auto_scale_ai_castle(game)
        result["ai_castle"].append({"wave": wave, "level": castle.level})
        result["ai_income"].append({
            "wave": wave, "gold": eval(income_expr, vars(core), {"self": game}),
        })
    for lane, points in zip(("top", "mid", "bot"), paths.generate_lanes(1280, 720)):
        result["lane_endpoints"][lane] = {"blue": list(points[0]), "red": list(points[-1])}
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-fixture", action="store_true")
    args = parser.parse_args()
    os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
    os.environ.setdefault("SDL_AUDIODRIVER", "dummy")
    os.environ.setdefault("PYGAME_HIDE_SUPPORT_PROMPT", "1")
    sys.path.insert(0, str(ROOT))
    # Match the isolation pattern in test_easy_mode_ai_pool.py: the one-time
    # save migrator must not read or copy a developer's real ./saves directory.
    with tempfile.TemporaryDirectory(prefix="mystic-godot-parity-") as save_dir:
        os.environ["MYSTIC_SAVE_DIR"] = save_dir
        cwd = os.getcwd()
        os.chdir(save_dir)
        try:
            import _core as core
            import _entity as entity
            import levels
            from map_components.generators import PathGenerator
            expected = make_fixture(core, entity, levels, PathGenerator)
        finally:
            os.chdir(cwd)
        economy = json.loads((ROOT / "godot/data/economy.json").read_text())
        for key, actual in {
            "starting_gold": core.STARTING_GOLD,
            "minion_wave_interval_frames": core.MINION_WAVE_INTERVAL,
            "minion_spawn_delay_frames": core.MINION_SPAWN_DELAY,
            "max_heroes_owned": core.MAX_HEROES_OWNED,
        }.items():
            assert economy[key] == actual, f"Re-export economy.json: {key} drifted"
    if args.write_fixture:
        FIXTURE.parent.mkdir(parents=True, exist_ok=True)
        FIXTURE.write_text(json.dumps(expected, indent=2, ensure_ascii=False) + "\n")
        print(f"Wrote {FIXTURE.relative_to(ROOT)}")
    else:
        actual = json.loads(FIXTURE.read_text())
        assert actual == expected, (
            "Pygame gameplay changed. Review the Godot implementation, then run "
            "tools/test_godot_match_parity.py --write-fixture")
        print("[PygameMatchParity] PASS: fixture matches Pygame rules, all 54 levels, "
              "50 wave compositions and 25 minion/nexus combinations")


if __name__ == "__main__":
    main()
